spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MetaForgeTest
    username: metaforge
    password: metaforge
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
