spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  test:
    database:
      replace: any
metaforge:
  test:
    random:
      seed: 1
    database:
      users:
        amount: 1_000
      libraries:
        amount: 1_000
      visits:
        amount: 1_000


